services:
  - type: web
    name: mohr-hr-v2
    env: node
    plan: free
    buildCommand: npm install && cd backend && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: DB_TYPE
        value: sqlite
      - key: CORS_ORIGIN
        value: "*"
      - key: GOOGLE_CALLBACK_URL
        value: https://mohr-hr-v2.onrender.com/auth/google/callback
      - key: FRONTEND_URL
        value: https://mohr-hr-v2.onrender.com
    healthCheckPath: /api/health
    autoDeploy: true 